[package]
name = "rhizomedb-benches"
version = "0.0.0"
publish = false
edition = "2021"
authors = ["Quinn Wilton <quinn@quinnwilton.com>"]

[dependencies]

[dev-dependencies]
criterion = { version = "0.4", default-features = false }

[[bench]]
name = "a_benchmark"
harness = false
