[package]
name = "rhizomedb-tokio"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0 or MIT"

[lib]
path = "src/lib.rs"

[dependencies]

[dev-dependencies]
pretty_assertions = "1.3.0"
serde_json = "1.0"
tokio-tungstenite = "0.18"
tungstenite = "0.18"
